#!/bin/bash
#adding HCI_UART kernel module
sudo modprobe hci_uart
sleep 2
#to show all loaded kernel modules 
lsmod
#attach UART to Bluetooth stack as HCI transport interface
hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -
sleep 2
#Run Bluetooth Daemon
/usr/libexec/bluetooth/bluetoothd &
sleep 2
#Bring up HCI Interface
hciconfig hci0 up
sleep 2


