#!/bin/sh
#
# updating songs initscript
#
### BEGIN INIT INFO
# Provides:          running updating songs script
# Required-Start:    
# Required-Stop:     
# Default-Start:     
# Default-Stop:      
# Short-Description: Running python script
# Description:       This script runs python script to monitor changes 
#		     in mp3 files and append them to the required text file		     
### END INIT INFO



./mp3Files/mp3main2 

